export const PRODUCT_REQUEST = "PRODUCT_REQUEST";
export const PRODUCT_FAILURE = "PRODUCT_FAILURE";
export const GET_PRODUCT_SUCCSES = "GET_PRODUCT_SUCCSES";
export const PATCH_PRODUCT_SUCCSES = "PATCH_PRODUCT_SUCCSES";
export const DELETE_PRODUCT_SUCCSES = "DELETE_PRODUCT_SUCCSES";
export const POST_PRODUCT_SUCCSES = "DELETE_PRODUCT_SUCCSES";
