export const LOAN_DATA_REQUEST = "LOAN_DATA_REQUEST"
export const LOAN_DATA_SUCCESS = "LOAN_DATA_SUCCESS"
export const LOAN_DATA_ERROR = "LOAN_DATA_ERROR"

export const GET_LOAN_DATA_REQUEST = "GET_LOAN_DATA_REQUEST"
export const GET_LOAN_DATA_SUCCESS = "GET_LOAN_DATA_SUCCESS"
export const GET_LOAN_DATA_ERROR = "GET_LOAN_DATA_ERROR"

export const ALL_USER_REQUEST = "ALL_USER_REQUEST"
export const ALL_USER_SUCCESS = "ALL_USER_SUCCESS"
export const ALL_USER_ERROR = "ALL_USER_ERROR"

export const BANK_DATA_REQUEST = "BANK_DATA_REQUEST"
export const BANK_DATA_SUCCESS = "BANK_DATA_SUCCESS"
export const BANK_DATA_ERROR = "BANK_DATA_ERROR"

export const CURRENT_USER_SUCCESS = "CURRENT_USER_SUCCESS"